server {
    listen 80;
    server_name ramonbuzo.tech www.ramonbuzo.tech;
    root /usr/share/nginx/dashboard;
    index index.html;
}

server {
    listen 80;
    server_name me.ramonbuzo.tech;
    root /usr/share/nginx/portfolio;
    index index.html;
}
